const SESSION_DAYS = 30;
const json = (data, status = 200, headers = {}) => new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json; charset=utf-8", ...headers } });
const cookie = (name, value, maxAge = SESSION_DAYS * 86400) => `${name}=${value}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Lax`;
const readCookie = (request, name) => request.headers.get("Cookie")?.split(";").map((v) => v.trim()).find((v) => v.startsWith(`${name}=`))?.slice(name.length + 1) || null;
const hex = (bytes) => [...new Uint8Array(bytes)].map((b) => b.toString(16).padStart(2, "0")).join("");
const randomHex = (size = 16) => hex(crypto.getRandomValues(new Uint8Array(size)));
const digest = async (value) => hex(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)));
async function hashPassword(password, salt) { const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, ["deriveBits"]); const bits = await crypto.subtle.deriveBits({ name: "PBKDF2", salt: new TextEncoder().encode(salt), iterations: 100000, hash: "SHA-256" }, key, 256); return hex(bits); }
const body = async (request) => { try { return await request.json(); } catch { return {}; } };
async function currentUser(request, db) { const token = readCookie(request, "fitpath_session"); if (!token) return null; const session = await db.prepare("SELECT user_id FROM sessions WHERE token_hash = ? AND expires_at > datetime('now')").bind(await digest(token)).first(); return session ? db.prepare("SELECT id, username, name, created_at FROM users WHERE id = ?").bind(session.user_id).first() : null; }
async function api(request, env, url) {
  if (!env.DB) return json({ error: "D1 데이터베이스가 아직 연결되지 않았어요." }, 503); const db = env.DB; const path = url.pathname;
  if (request.method === "POST" && path === "/api/auth/signup") { const data = await body(request); const name = String(data.name || "").trim().slice(0, 40); const username = String(data.username || "").trim().toLowerCase().slice(0, 40); const password = String(data.password || ""); if (name.length < 1 || username.length < 3 || password.length < 8) return json({ error: "이름, 아이디(3자 이상), 비밀번호(8자 이상)를 확인해 주세요." }, 400); const salt = randomHex(16); const passwordHash = await hashPassword(password, salt); try { const result = await db.prepare("INSERT INTO users (username, name, password_hash, password_salt) VALUES (?, ?, ?, ?)").bind(username, name, passwordHash, salt).run(); const token = randomHex(32); await db.prepare("INSERT INTO sessions (token_hash, user_id, expires_at) VALUES (?, ?, datetime('now', '+30 days'))").bind(await digest(token), result.meta.last_row_id).run(); return json({ user: { id: result.meta.last_row_id, username, name } }, 201, { "set-cookie": cookie("fitpath_session", token) }); } catch (error) { if (String(error).includes("UNIQUE")) return json({ error: "이미 사용 중인 아이디예요." }, 409); throw error; } }
  if (request.method === "POST" && path === "/api/auth/login") { const data = await body(request); const username = String(data.username || "").trim().toLowerCase(); const password = String(data.password || ""); const user = await db.prepare("SELECT id, username, name, password_hash, password_salt FROM users WHERE username = ?").bind(username).first(); if (!user || (await hashPassword(password, user.password_salt)) !== user.password_hash) return json({ error: "아이디 또는 비밀번호를 확인해 주세요." }, 401); const token = randomHex(32); await db.prepare("INSERT INTO sessions (token_hash, user_id, expires_at) VALUES (?, ?, datetime('now', '+30 days'))").bind(await digest(token), user.id).run(); return json({ user: { id: user.id, username: user.username, name: user.name } }, 200, { "set-cookie": cookie("fitpath_session", token) }); }
  if (request.method === "POST" && path === "/api/auth/logout") { const token = readCookie(request, "fitpath_session"); if (token) await db.prepare("DELETE FROM sessions WHERE token_hash = ?").bind(await digest(token)).run(); return json({ ok: true }, 200, { "set-cookie": cookie("fitpath_session", "", 0) }); }
  const user = await currentUser(request, db); if (!user) return json({ error: "로그인이 필요해요." }, 401);
  if (request.method === "GET" && path === "/api/auth/me") return json({ user });
  if (request.method === "GET" && path === "/api/records") { const snapshots = await db.prepare("SELECT payload, created_at FROM snapshots WHERE user_id = ? ORDER BY created_at DESC LIMIT 30").bind(user.id).all(); const checkins = await db.prepare("SELECT payload, created_at FROM checkins WHERE user_id = ? ORDER BY created_at DESC LIMIT 52").bind(user.id).all(); return json({ snapshots: snapshots.results.map((r) => ({ ...JSON.parse(r.payload), createdAt: r.created_at })), checkins: checkins.results.map((r) => ({ ...JSON.parse(r.payload), createdAt: r.created_at })) }); }
  if (request.method === "POST" && path === "/api/records/snapshot") { const data = await body(request); await db.prepare("INSERT INTO snapshots (user_id, payload) VALUES (?, ?)").bind(user.id, JSON.stringify(data.snapshot || {})).run(); return json({ ok: true }); }
  if (request.method === "POST" && path === "/api/records/checkin") { const data = await body(request); await db.prepare("INSERT INTO checkins (user_id, payload) VALUES (?, ?)").bind(user.id, JSON.stringify(data.checkin || {})).run(); return json({ ok: true }); }
  return json({ error: "Not found" }, 404);
}
export default { async fetch(request, env) { const url = new URL(request.url); if (url.pathname.startsWith("/api/")) { try { return await api(request, env, url); } catch (error) { return json({ error: "서버에서 처리하지 못했어요.", detail: env.ENVIRONMENT === "development" ? String(error) : undefined }, 500); } } return env.ASSETS.fetch(request); } };
