import * as bcrypt from "bcryptjs";
const json=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json; charset=utf-8",...h}});
const cookie=(v,max=2592000)=>`fitpath_session=${v}; Path=/; Max-Age=${max}; HttpOnly; Secure; SameSite=Lax`;
const tokenFrom=(r)=>r.headers.get("Cookie")?.split(";").map(x=>x.trim()).find(x=>x.startsWith("fitpath_session="))?.slice(16)||null;
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");
const random=()=>hex(crypto.getRandomValues(new Uint8Array(32)));
const digest=async v=>hex(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v)));
const body=async r=>{try{return await r.json()}catch{return{}}};
async function userFor(r,db){const t=tokenFrom(r);if(!t)return null;const s=await db.prepare("SELECT user_id FROM sessions WHERE token_hash=? AND expires_at>datetime('now')").bind(await digest(t)).first();return s?db.prepare("SELECT id,username,name,created_at FROM users WHERE id=?").bind(s.user_id).first():null}
async function api(r,e,u){if(!e.DB)return json({error:"D1 연결이 필요해요."},503);const db=e.DB,p=u.pathname;
 if(r.method==="POST"&&p==="/api/auth/signup"){const d=await body(r),name=String(d.name||"").trim().slice(0,40),username=String(d.username||"").trim().toLowerCase().slice(0,40),password=String(d.password||"");if(name.length<1||username.length<3||password.length<8)return json({error:"이름, 아이디(3자 이상), 비밀번호(8자 이상)를 확인해 주세요."},400);try{const q=await db.prepare("INSERT INTO users (username,name,password_hash) VALUES (?,?,?)").bind(username,name,await bcrypt.hash(password,12)).run(),t=random();await db.prepare("INSERT INTO sessions (token_hash,user_id,expires_at) VALUES (?,?,datetime('now','+30 days'))").bind(await digest(t),q.meta.last_row_id).run();return json({user:{id:q.meta.last_row_id,username,name}},201,{"set-cookie":cookie(t)})}catch(x){if(String(x).includes("UNIQUE"))return json({error:"이미 사용 중인 아이디예요."},409);throw x}}
 if(r.method==="POST"&&p==="/api/auth/login"){const d=await body(r),username=String(d.username||"").trim().toLowerCase(),u0=await db.prepare("SELECT id,username,name,password_hash FROM users WHERE username=?").bind(username).first();if(!u0||!(await bcrypt.compare(String(d.password||""),u0.password_hash)))return json({error:"아이디 또는 비밀번호를 확인해 주세요."},401);const t=random();await db.prepare("INSERT INTO sessions (token_hash,user_id,expires_at) VALUES (?,?,datetime('now','+30 days'))").bind(await digest(t),u0.id).run();return json({user:{id:u0.id,username:u0.username,name:u0.name}},200,{"set-cookie":cookie(t)})}
 if(r.method==="POST"&&p==="/api/auth/logout"){const t=tokenFrom(r);if(t)await db.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await digest(t)).run();return json({ok:true},200,{"set-cookie":cookie("",0)})}
 const u0=await userFor(r,db);if(!u0)return json({error:"로그인이 필요해요."},401);
 if(r.method==="GET"&&p==="/api/auth/me")return json({user:u0});
 if(r.method==="GET"&&p==="/api/records"){const [a,c,o]=await Promise.all([db.prepare("SELECT payload,created_at FROM snapshots WHERE user_id=? ORDER BY created_at DESC LIMIT 30").bind(u0.id).all(),db.prepare("SELECT payload,created_at FROM checkins WHERE user_id=? ORDER BY created_at DESC LIMIT 52").bind(u0.id).all(),db.prepare("SELECT payload,created_at FROM orders WHERE user_id=? ORDER BY created_at DESC LIMIT 50").bind(u0.id).all()]);return json({snapshots:a.results.map(x=>({...JSON.parse(x.payload),createdAt:x.created_at})),checkins:c.results.map(x=>({...JSON.parse(x.payload),createdAt:x.created_at})),orders:o.results.map(x=>({...JSON.parse(x.payload),createdAt:x.created_at}))})}
 if(r.method==="POST"&&p==="/api/records/snapshot") {const d=await body(r);await db.prepare("INSERT INTO snapshots(user_id,payload) VALUES(?,?)").bind(u0.id,JSON.stringify(d.snapshot||{})).run();return json({ok:true})}
 if(r.method==="POST"&&p==="/api/records/checkin") {const d=await body(r);await db.prepare("INSERT INTO checkins(user_id,payload) VALUES(?,?)").bind(u0.id,JSON.stringify(d.checkin||{})).run();return json({ok:true})}
 if(r.method==="GET"&&p==="/api/orders") {const a=await db.prepare("SELECT payload,created_at FROM orders WHERE user_id=? ORDER BY created_at DESC LIMIT 50").bind(u0.id).all();return json({orders:a.results.map(x=>({...JSON.parse(x.payload),createdAt:x.created_at}))})}
 if(r.method==="POST"&&p==="/api/orders") {const d=await body(r);await db.prepare("INSERT INTO orders(user_id,payload) VALUES(?,?)").bind(u0.id,JSON.stringify(d.order||{})).run();return json({ok:true})}return json({error:"Not found"},404)}
export default{async fetch(r,e){const u=new URL(r.url);if(u.pathname.startsWith("/api/"))try{return await api(r,e,u)}catch(x){return json({error:"서버에서 처리하지 못했어요."},500)}return e.ASSETS.fetch(r)}};
